version: 2.1

# basic env
workspace: &workspace ~/nju-se-17-advanced-se/frontend

# image
step_docker_login: &docker_login
  run: |
    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin registry.cn-hangzhou.aliyuncs.com

# SSH
step_add_ssh: &add_ssh
  add_ssh_keys:
    fingerprints:
      - $SSH_FINGERPRINT

step_deploy_over_ssh: &deploy_over_ssh
  run:
    name: Deploy Over SSH
    command: |
      ssh $SSH_USER@$SSH_HOST < ci/service-restart.sh

jobs:
  deploy:
    machine:
      enabled: true
    working_directory: *workspace
    steps:
      - checkout
      - *docker_login
      - *add_ssh
      - *deploy_over_ssh

workflows:
  release-frontend:
    jobs:
      - deploy:
          context:
            - WenSun阿里云1核2G
          filters:
            branches:
              only:
                - master
